//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etech.CMS.Web.admin {
    
    
    public partial class newsletterTemplates {
        
        /// <summary>
        /// pnlEditTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Panel pnlEditTemplate;
        
        /// <summary>
        /// lblDuplicateMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblDuplicateMessage;
        
        /// <summary>
        /// lblTemplateTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblTemplateTitle;
        
        /// <summary>
        /// lblTemplateId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblTemplateId;
        
        /// <summary>
        /// txtTemplateTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.TextBox txtTemplateTitle;
        
        /// <summary>
        /// rfvTempalteTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.RequiredFieldValidator rfvTempalteTitle;
        
        /// <summary>
        /// refTemplateTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator refTemplateTitle;
        
        /// <summary>
        /// lblTemplateTags control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblTemplateTags;
        
        /// <summary>
        /// ddlTemplateTag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.DropDownList ddlTemplateTag;
        
        /// <summary>
        /// lnkInsertTag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.LinkButton lnkInsertTag;
        
        /// <summary>
        /// lblTemplateDescriptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblTemplateDescriptions;
        
        /// <summary>
        /// txtDescriptor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FredCK.FCKeditorV2.FCKeditor txtDescriptor;
        
        /// <summary>
        /// cvcfckAText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator cvcfckAText;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Button btnSave;
        
        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Button btnCancel;
        
        /// <summary>
        /// pnlCurrentTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Panel pnlCurrentTemplate;
        
        /// <summary>
        /// lnkAddTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.LinkButton lnkAddTemplate;
        
        /// <summary>
        /// dgTemplates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.DataGrid dgTemplates;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Etech.CMS.Web.admin.admin Master {
            get {
                return ((Etech.CMS.Web.admin.admin)(base.Master));
            }
        }
    }
}
