//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etech.CMS.Web {
    
    
    public partial class Home {
        
        /// <summary>
        /// contentPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder contentPlaceHolder;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        /// 
        //public new Etech.CMS.Web.site Master {
        //    get {
        //        return ((Etech.CMS.Web.site)(base.Master));
        //    }
        //}

        public new Etech.CMS.Store.Web.SiteMasterPage Master
        {
            get
            {
                return ((Etech.CMS.Store.Web.SiteMasterPage)(base.Master));
            }
        }
    }
}
