//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etech.CMS.Web.admin.controls.sitesettings {
    
    
    public partial class site {
        
        /// <summary>
        /// pnlSite control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Panel pnlSite;
        
        /// <summary>
        /// lblStoreClosed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblStoreClosed;
        
        /// <summary>
        /// chkStoreClosed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.CheckBox chkStoreClosed;
        
        /// <summary>
        /// helpStoreClosed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpStoreClosed;
        
        /// <summary>
        /// lblLogo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblLogo;
        
        /// <summary>
        /// txtLogo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtLogo;
        
        /// <summary>
        /// hlImageSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HyperLink hlImageSelector;
        
        /// <summary>
        /// helpSiteLogo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpSiteLogo;
        
        /// <summary>
        /// lblName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblName;
        
        /// <summary>
        /// txtName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtName;
        
        /// <summary>
        /// helpSiteName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpSiteName;
        
        /// <summary>
        /// lblTagLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblTagLine;
        
        /// <summary>
        /// txtTagLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTagLine;
        
        /// <summary>
        /// helpTagLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpTagLine;
        
        /// <summary>
        /// lblLoginRequirement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblLoginRequirement;
        
        /// <summary>
        /// ddlLoginRequirement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlLoginRequirement;
        
        /// <summary>
        /// helpLoginRequirement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpLoginRequirement;
        
        /// <summary>
        /// lblRequireSsl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblRequireSsl;
        
        /// <summary>
        /// chkRequireSsl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.CheckBox chkRequireSsl;
        
        /// <summary>
        /// helpRequireSsl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpRequireSsl;
        
        /// <summary>
        /// lblDisplayRetailPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblDisplayRetailPrice;
        
        /// <summary>
        /// chkDisplayRetailPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.CheckBox chkDisplayRetailPrice;
        
        /// <summary>
        /// helpDisplayRetailPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpDisplayRetailPrice;
        
        /// <summary>
        /// lblAddTaxToPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblAddTaxToPrice;
        
        /// <summary>
        /// chkAddTaxToPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.CheckBox chkAddTaxToPrice;
        
        /// <summary>
        /// helpAddTaxToPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpAddTaxToPrice;
        
        /// <summary>
        /// lblDisplayRatings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblDisplayRatings;
        
        /// <summary>
        /// chkDisplayRatings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.CheckBox chkDisplayRatings;
        
        /// <summary>
        /// helpDisplayRatings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpDisplayRatings;
        
        /// <summary>
        /// lblShowShippingOnCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblShowShippingOnCart;
        
        /// <summary>
        /// chkDisplayShippingOnCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.CheckBox chkDisplayShippingOnCart;
        
        /// <summary>
        /// helpDisplayShippingOnCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpDisplayShippingOnCart;
        
        /// <summary>
        /// lblCategoryItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblCategoryItems;
        
        /// <summary>
        /// ddlCategoryItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoryItems;
        
        /// <summary>
        /// helpCategoryItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpCategoryItems;
        
        /// <summary>
        /// lblDefaultCategorySorting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblDefaultCategorySorting;
        
        /// <summary>
        /// ddlDefaultSort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlDefaultSort;
        
        /// <summary>
        /// lblMaximumProductsToAddToCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblMaximumProductsToAddToCart;
        
        /// <summary>
        /// txtMaximumProductsToAddToCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtMaximumProductsToAddToCart;
        
        /// <summary>
        /// ftbeMaximumProductsToAddToCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender ftbeMaximumProductsToAddToCart;
        
        /// <summary>
        /// helpMaximumProductsToAddToCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpMaximumProductsToAddToCart;
        
        /// <summary>
        /// lblTheme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblTheme;
        
        /// <summary>
        /// ddlTheme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlTheme;
        
        /// <summary>
        /// helpTheme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpTheme;
        
        /// <summary>
        /// lblNewsFeedUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblNewsFeedUrl;
        
        /// <summary>
        /// txtNewsFeedUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNewsFeedUrl;
        
        /// <summary>
        /// helpNewsFeedUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpNewsFeedUrl;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Button btnSave;
    }
}
