//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class adminNav {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal adminNav() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.adminNav", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Categories.
        /// </summary>
        internal static string BlogCategories {
            get {
                return ResourceManager.GetString("BlogCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Configuration.
        /// </summary>
        internal static string CacheConfiguration {
            get {
                return ResourceManager.GetString("CacheConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.com.
        /// </summary>
        internal static string CMScom {
            get {
                return ResourceManager.GetString("CMScom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.org.
        /// </summary>
        internal static string CMSorg {
            get {
                return ResourceManager.GetString("CMSorg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Banner.
        /// </summary>
        internal static string CommonBanner {
            get {
                return ResourceManager.GetString("CommonBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Forums.
        /// </summary>
        internal static string CommunityForums {
            get {
                return ResourceManager.GetString("CommunityForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Cache Providers.
        /// </summary>
        internal static string ConfigureCacheProviders {
            get {
                return ResourceManager.GetString("ConfigureCacheProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Payment Providers.
        /// </summary>
        internal static string ConfigurePaymentProviders {
            get {
                return ResourceManager.GetString("ConfigurePaymentProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Shipping Providers.
        /// </summary>
        internal static string ConfigureShippingProviders {
            get {
                return ResourceManager.GetString("ConfigureShippingProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Tax Providers.
        /// </summary>
        internal static string ConfigureTaxProviders {
            get {
                return ResourceManager.GetString("ConfigureTaxProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Management.
        /// </summary>
        internal static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        internal static string Coupons {
            get {
                return ResourceManager.GetString("Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        internal static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        internal static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Logs.
        /// </summary>
        internal static string ErrorLogs {
            get {
                return ResourceManager.GetString("ErrorLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Member.
        /// </summary>
        internal static string FullMember {
            get {
                return ResourceManager.GetString("FullMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliates Categories.
        /// </summary>
        internal static string GalleryCategory {
            get {
                return ResourceManager.GetString("GalleryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GallerySubCategory.
        /// </summary>
        internal static string GallerySubCategory {
            get {
                return ResourceManager.GetString("GallerySubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Cache Settings.
        /// </summary>
        internal static string GeneralCacheProviderSettings {
            get {
                return ResourceManager.GetString("GeneralCacheProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Payment Settings.
        /// </summary>
        internal static string GeneralPaymentProviderSettings {
            get {
                return ResourceManager.GetString("GeneralPaymentProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Shipping Settings.
        /// </summary>
        internal static string GeneralShippingProviderSettings {
            get {
                return ResourceManager.GetString("GeneralShippingProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Tax Settings.
        /// </summary>
        internal static string GeneralTaxProviderSettings {
            get {
                return ResourceManager.GetString("GeneralTaxProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Affiliates Gallery.
        /// </summary>
        internal static string ImageGallary {
            get {
                return ResourceManager.GetString("ImageGallary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Configuration.
        /// </summary>
        internal static string MailConfiguration {
            get {
                return ResourceManager.GetString("MailConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Settings.
        /// </summary>
        internal static string MailSettings {
            get {
                return ResourceManager.GetString("MailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Cache Providers.
        /// </summary>
        internal static string ManageCacheProviders {
            get {
                return ResourceManager.GetString("ManageCacheProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Coupon Providers.
        /// </summary>
        internal static string ManageCouponProviders {
            get {
                return ResourceManager.GetString("ManageCouponProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Payment Providers.
        /// </summary>
        internal static string ManagePaymentProviders {
            get {
                return ResourceManager.GetString("ManagePaymentProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Shipping Providers.
        /// </summary>
        internal static string ManageShippingProviders {
            get {
                return ResourceManager.GetString("ManageShippingProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tax Providers.
        /// </summary>
        internal static string ManageTaxProviders {
            get {
                return ResourceManager.GetString("ManageTaxProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Meetings.
        /// </summary>
        internal static string MonthlyMeeting {
            get {
                return ResourceManager.GetString("MonthlyMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp;#38; Event.
        /// </summary>
        internal static string NewsEvent {
            get {
                return ResourceManager.GetString("NewsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        internal static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletters.
        /// </summary>
        internal static string NewsLetters {
            get {
                return ResourceManager.GetString("NewsLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletters Templates.
        /// </summary>
        internal static string NewsLetters_Templates {
            get {
                return ResourceManager.GetString("NewsLetters Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter Group.
        /// </summary>
        internal static string NewsLetter_Group {
            get {
                return ResourceManager.GetString("NewsLetter Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter Users.
        /// </summary>
        internal static string NewsLetter_Users {
            get {
                return ResourceManager.GetString("NewsLetter Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Search.
        /// </summary>
        internal static string OrderSearch {
            get {
                return ResourceManager.GetString("OrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Configuration.
        /// </summary>
        internal static string PaymentConfiguration {
            get {
                return ResourceManager.GetString("PaymentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Payment Configuration.
        /// </summary>
        internal static string PayPalPaymentConfiguration {
            get {
                return ResourceManager.GetString("PayPalPaymentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Attributes.
        /// </summary>
        internal static string ProductAttributes {
            get {
                return ResourceManager.GetString("ProductAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Bundles.
        /// </summary>
        internal static string ProductBundles {
            get {
                return ResourceManager.GetString("ProductBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Campaigns ?.
        /// </summary>
        internal static string ProductCampaigns {
            get {
                return ResourceManager.GetString("ProductCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories.
        /// </summary>
        internal static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Coupons.
        /// </summary>
        internal static string ProductCoupons {
            get {
                return ResourceManager.GetString("ProductCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Downloads.
        /// </summary>
        internal static string ProductDownloads {
            get {
                return ResourceManager.GetString("ProductDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Listing.
        /// </summary>
        internal static string ProductListing {
            get {
                return ResourceManager.GetString("ProductListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Management.
        /// </summary>
        internal static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Manufacturers.
        /// </summary>
        internal static string ProductManufacturers {
            get {
                return ResourceManager.GetString("ProductManufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Promotions ?.
        /// </summary>
        internal static string ProductPromotions {
            get {
                return ResourceManager.GetString("ProductPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Reviews ?.
        /// </summary>
        internal static string ProductReviews {
            get {
                return ResourceManager.GetString("ProductReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Site.
        /// </summary>
        internal static string ReturnToSite {
            get {
                return ResourceManager.GetString("ReturnToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Administration.
        /// </summary>
        internal static string RoleAdministration {
            get {
                return ResourceManager.GetString("RoleAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string ServicesCategory {
            get {
                return ResourceManager.GetString("ServicesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServicesDetail.
        /// </summary>
        internal static string ServicesDetail {
            get {
                return ResourceManager.GetString("ServicesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Configuration.
        /// </summary>
        internal static string ShippingConfiguration {
            get {
                return ResourceManager.GetString("ShippingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Configuration.
        /// </summary>
        internal static string SiteConfiguration {
            get {
                return ResourceManager.GetString("SiteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        internal static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Settings.
        /// </summary>
        internal static string StoreSettings {
            get {
                return ResourceManager.GetString("StoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Configuration.
        /// </summary>
        internal static string TaxConfiguration {
            get {
                return ResourceManager.GetString("TaxConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Affiliate Meetings/Latest News.
        /// </summary>
        internal static string testimonials {
            get {
                return ResourceManager.GetString("testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Logs.
        /// </summary>
        internal static string TrackingLogs {
            get {
                return ResourceManager.GetString("TrackingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        internal static string UserAdministration {
            get {
                return ResourceManager.GetString("UserAdministration", resourceCulture);
            }
        }
    }
}
