//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etech.CMS.Web.admin.controls.Gallary {
    
    
    public partial class ImageGallary {
        
        /// <summary>
        /// pnlEditPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Panel pnlEditPage;
        
        /// <summary>
        /// lblImageId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblImageId;
        
        /// <summary>
        /// lblImageFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblImageFile;
        
        /// <summary>
        /// txtImageFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtImageFile;
        
        /// <summary>
        /// hlImageSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HyperLink hlImageSelector;
        
        /// <summary>
        /// helpImageFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpImageFile;
        
        /// <summary>
        /// btnBigDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Button btnBigDelete;
        
        /// <summary>
        /// lblTumbFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblTumbFile;
        
        /// <summary>
        /// txtTumbImageFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTumbImageFile;
        
        /// <summary>
        /// hlThumbImageSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HyperLink hlThumbImageSelector;
        
        /// <summary>
        /// helpThumbImageFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpThumbImageFile;
        
        /// <summary>
        /// btnDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Button btnDelete;
        
        /// <summary>
        /// lblImageCaption control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblImageCaption;
        
        /// <summary>
        /// helpImageCaption control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink helpImageCaption;
        
        /// <summary>
        /// txtImageCaption control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtImageCaption;
        
        /// <summary>
        /// revImageCaption control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revImageCaption;
        
        /// <summary>
        /// lblImgCategoryID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblImgCategoryID;
        
        /// <summary>
        /// ddlImgCategoryID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.DropDownList ddlImgCategoryID;
        
        /// <summary>
        /// rfvImgCategoryID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.RequiredFieldValidator rfvImgCategoryID;
        
        /// <summary>
        /// lblFooterSponsorURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblFooterSponsorURLTitle;
        
        /// <summary>
        /// hlImageURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink hlImageURLTitle;
        
        /// <summary>
        /// txtURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtURLTitle;
        
        /// <summary>
        /// regexURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator regexURLTitle;
        
        /// <summary>
        /// chkLeftSponsorImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkLeftSponsorImage;
        
        /// <summary>
        /// lblIsDownload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblIsDownload;
        
        /// <summary>
        /// hlLeftSponsorImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink hlLeftSponsorImage;
        
        /// <summary>
        /// lblLeftSponsorURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Label lblLeftSponsorURLTitle;
        
        /// <summary>
        /// hlLeftSponsorURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.HelpLink hlLeftSponsorURLTitle;
        
        /// <summary>
        /// txtLeftSponsorURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtLeftSponsorURLTitle;
        
        /// <summary>
        /// revLeftSponsorURLTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revLeftSponsorURLTitle;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Button btnSave;
        
        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Button btnCancel;
        
        /// <summary>
        /// pnlImages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.Panel pnlImages;
        
        /// <summary>
        /// lnkAddTherapists control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.LinkButton lnkAddTherapists;
        
        /// <summary>
        /// dgProductImages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Etech.CMS.Controls.DataGrid dgProductImages;
    }
}
